### ISSUE TITLE
hexo启动报错找不到gitment

### ISSUE THREAD

**Issue by xiaopf** [dusign/hexo-theme-snail#2]
https://github.com/dusign/hexo-theme-snail/blob/08cf7adbe65363b8bcae02441f2564796a82d160/_config.yml#L188-L199
这个地方 gitment livere disqus 应该缩进吧，他们是在comment上的，否则我这边报错找不到 gitment等。

**Comment by dusign** [comment]
> https://github.com/dusign/hexo-theme-snail/blob/08cf7adbe65363b8bcae02441f2564796a82d160/_config.yml#L188-L199
> 
> 
> 这个地方 gitment livere disqus 应该缩进吧，他们是在comment上的，否则我这边报错找不到 gitment等。

对的，需要缩进

**Comment by dusign** [comment]
> > https://github.com/dusign/hexo-theme-snail/blob/08cf7adbe65363b8bcae02441f2564796a82d160/_config.yml#L188-L199
> > 
> > 这个地方 gitment livere disqus 应该缩进吧，他们是在comment上的，否则我这边报错找不到 gitment等。
> 
> 对的，需要缩进

按照我的说明文档设置就行
