### ISSUE TITLE
右上角的CHINESE　BLOG问题

### ISSUE THREAD

**Issue by Beyonderwei** [dusign/hexo-theme-snail#4]
作者你好，觉得你做的主题很漂亮，我不过我遇到了一个使用问题，想问一下右上角的CHINESE　BLOG如何更改href或者去掉呢？

**Comment by dusign** [comment]
> 作者你好，觉得你做的主题很漂亮，我不过我遇到了一个使用问题，想问一下右上角的CHINESE　BLOG如何更改href或者去掉呢？

我晚上更新吧，之后会把chinese blog的配置放到config文件里

**Comment by dusign** [comment]
<img width="481" alt="chinese_blog" src="https://user-images.githubusercontent.com/43838747/75131099-6392a380-570c-11ea-9be7-8ce3744c89fa.png">
