### ISSUE TITLE
首頁預覽下的hover特效

### ISSUE THREAD

**Issue by john850512** [dusign/hexo-theme-snail#7]
作者你好，首頁預覽下滑鼠移到文章內容上會字體會變成藍色，並且有超連結可以直接點進去的效果。
[在你的網站中](https://www.dusign.net/)也可以看到這樣的效果。
![Imgur](https://i.imgur.com/f3dsGyT.png)

如果想把這個功能關掉的話(也就是滑鼠移到時字體不會變藍色也不會有進入的超連結)，請問有辦法可以修改嗎?

**Comment by dusign** [comment]
> 作者你好，首頁預覽下滑鼠移到文章內容上會字體會變成藍色，並且有超連結可以直接點進去的效果。
> [在你的網站中](https://www.dusign.net/)也可以看到這樣的效果。
> ![Imgur](https://camo.githubusercontent.com/9fe762e47bfe3530738f47caf2cfd191b934e7e6/68747470733a2f2f692e696d6775722e636f6d2f663364734779542e706e67)
> 
> 如果想把這個功能關掉的話(也就是滑鼠移到時字體不會變藍色也不會有進入的超連結)，請問有辦法可以修改嗎?

这个只能修改样式文件

**Comment by john850512** [comment]
謝謝回覆，已解決，修改`/snail/layout/index.ejs` ，將
`<div class="post-preview">`後的`<a href=...>`和`<\a>`

註解掉即可。
```javascript=10
      <div class="post-preview">
             /* <a href="<%- config.root %><%- post.path %>"> */
                <h2 class="post-title">
                    <img class="top_logo" src="/img/tp.png"/>
                    &nbsp;&nbsp;&nbsp;&nbsp;<%- post.title || "Untitled" %>
                </h2>
                <h3 class="post-subtitle">
                    <%- post.subtitle || "" %>
                </h3>
                <div class="post-content-preview">
                    <%- truncate(strip_html(post.content), {length: 200, omission: '...'}) %>...
                </div>
           /* </a> */
```
