### ISSUE TITLE
music接口无法获取到歌曲

### ISSUE THREAD

**Issue by jackandsnow** [dusign/hexo-theme-snail#8]
Request：
https://api.uomg.com/api/rand.music?sort=%E7%83%AD%E6%AD%8C%E6%A6%9C&format=json

Response：
{"code":1,"data":{"name":null,"url":"http:\/\/music.163.com\/song\/media\/outer\/url?id=.mp3","picurl":null,"artistsname":null}}

请问能够解决这个问题吗？

**Comment by dusign** [comment]
> Request：
> https://api.uomg.com/api/rand.music?sort=%E7%83%AD%E6%AD%8C%E6%A6%9C&format=json
> 
> Response：
> {"code":1,"data":{"name":null,"url":"http://music.163.com/song/media/outer/url?id=.mp3","picurl":null,"artistsname":null}}
> 
> 请问能够解决这个问题吗？

可以解决，网易云的api暂时没法用了，等我这两天的更新吧
